#!/usr/bin/env bash
###################################################################
# Run shellcheck on passed in files.
# Needed to ensure .config file is loaded
#
# Params
#   Files. path to one or more json files separated by spaces
###################################################################

# Stop on errors
set -e

printf 'Running %s with args %s\n' "$0" "$*"
py_ext=".py"
azcopy_dir="azcopy"
data_files_dir="data_files"

for i do

    # Skip files (azcopy|data_files|.py)
    if [[ $i == *$py_ext ]]; then
        break
    fi
    if [[ $i == *$azcopy_dir* ]]; then
        break
    fi
    if [[ $i == *$data_files_dir* ]]; then
        break
    fi

    if ! shellcheck "$i"; then
        echo "Shellcheck failed."
        exit 1
    fi
done
